# Generated by Django 4.2 on 2023-05-06 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.URLField()),
                ('shortened', models.URLField()),
                ('dateCreated', models.DateField()),
                ('hourCreated', models.TimeField()),
                ('urlUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.urluser')),
            ],
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navigator', models.CharField(max_length=100)),
                ('dateAccesed', models.DateField()),
                ('hourAccessed', models.TimeField()),
                ('ip', models.GenericIPAddressField()),
                ('shortenedURL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.shortenedurl')),
            ],
        ),
    ]
