# Generated by Django 4.2.1 on 2023-05-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='original',
            field=models.URLField(unique=True),
        ),
    ]
